on: [push, pull_request, workflow_dispatch]

name: R-CMD-quickcheck

jobs:
  R-CMD-check:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2-branch
      - uses: r-lib/actions/setup-pandoc@v2-branch
      - name: Install Cairo
        run: brew install cairo
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      - name: Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}
